// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRcJ4I_4XnoV93LN0RSgScfz-ske3yfpc',
    appId: '1:1059801849545:web:be7a155d3c915d303ff718',
    messagingSenderId: '1059801849545',
    projectId: 'kigali-city-services-cb9ab',
    authDomain: 'kigali-city-services-cb9ab.firebaseapp.com',
    storageBucket: 'kigali-city-services-cb9ab.firebasestorage.app',
    measurementId: 'G-1E0H1CP9W4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWUTk5eEH-Vu5aw1y_p8A6TYa6dJSdg_g',
    appId: '1:1059801849545:android:fb4a7682e55113fd3ff718',
    messagingSenderId: '1059801849545',
    projectId: 'kigali-city-services-cb9ab',
    storageBucket: 'kigali-city-services-cb9ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiNmwr7_tw2O-r3bHkb_n04DrDKRtn5vA',
    appId: '1:1059801849545:ios:02e28c9affb22ab83ff718',
    messagingSenderId: '1059801849545',
    projectId: 'kigali-city-services-cb9ab',
    storageBucket: 'kigali-city-services-cb9ab.firebasestorage.app',
    iosBundleId: 'com.example.kigaliCityServices',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiNmwr7_tw2O-r3bHkb_n04DrDKRtn5vA',
    appId: '1:1059801849545:ios:02e28c9affb22ab83ff718',
    messagingSenderId: '1059801849545',
    projectId: 'kigali-city-services-cb9ab',
    storageBucket: 'kigali-city-services-cb9ab.firebasestorage.app',
    iosBundleId: 'com.example.kigaliCityServices',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRcJ4I_4XnoV93LN0RSgScfz-ske3yfpc',
    appId: '1:1059801849545:web:5c57c918d9c2b8fb3ff718',
    messagingSenderId: '1059801849545',
    projectId: 'kigali-city-services-cb9ab',
    authDomain: 'kigali-city-services-cb9ab.firebaseapp.com',
    storageBucket: 'kigali-city-services-cb9ab.firebasestorage.app',
    measurementId: 'G-P156399208',
  );
}
